#!/usr/bin/env bash

uki="$3"
[[ -n "$uki" ]] || exit 0

keypairs=(/etc/pki/sbsign/db.key /etc/pki/sbsign/db.crt)

for (( i=0; i<${#keypairs[@]}; i+=2 )); do
	key="${keypairs[$i]}" cert="${keypairs[(( i + 1 ))]}"
	if ! sbverify --cert "$cert" "$uki" &> /dev/null; then
		sbsign --key "$key" --cert "$cert" --output "$uki" "$uki"
		echo "Added signature with $cert"
	else
		echo "Already signed with $cert"
	fi
done
